---
# tasks file for nginx
- name: Install the EPEL repository
  yum: name=epel-release state=present

- name: Install the Nginx package
  yum: name=nginx state=present

- name: Upload the nginx.conf modified file
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Upload the revese proxy configuration file
  template:
    src: reverse_proxy.conf.jn2
    dest: /etc/nginx/conf.d/reverse_proxy.conf
  notify: restart nginx

- name: Start and enable Nginx 
  service: name=nginx state=started enabled=yes